name: Caller Workflow

on:
  push: # Triggered on every push to the repository
    branches:
      - 'feature/*' # Match branches with naming convention

jobs:
  decide-and-call:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Cloud Provider from Branch Name
        id: extract
        run: |
          branch_name=${GITHUB_REF##*/}
          echo "Branch name: $branch_name"
          if [[ "$branch_name" == *azure* ]]; then
            echo "cloud_provider=Azure" >> $GITHUB_ENV
          elif [[ "$branch_name" == *aws* ]]; then
            echo "cloud_provider=AWS" >> $GITHUB_ENV
          else
            echo "Unknown cloud provider. Exiting."
            exit 1

  call-azure:
    if: ${{ env.cloud_provider == 'Azure' }}
    uses: m9ksh1t/github-actions-demo/.github/workflows/reuse1.yml@main

  call-aws:
    if: ${{ env.cloud_provider == 'AWS' }}
    uses: m9ksh1t/github-actions-demo/.github/workflows/reuse2.yml@main