name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: "Enter 1 to call reusable1 or 2 to call reusable2"
        required: true
        type: choice
        options:
          - "1"
          - "2"

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable1
        if: ${{ github.event.inputs.user_input == '1' }}
        uses: m9ksh1t/github-actions-demo/.github/workflows/reuse1.yml

      - name: Call Reusable2
        if: ${{ github.event.inputs.user_input == '2' }}
        uses: m9ksh1t/github-actions-demo/.github/workflows/reuse1.yml
