name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: "Enter 1 to call reusable1 or 2 to call reusable2"
        required: true
        type: choice
        options:
          - "1"
          - "2"

jobs:
  call-reusable1:
    if: ${{ github.event.inputs.user_input == '1' }}
    uses: m9ksh1t/github-actions-demo/.github/workflows/reuse1.yml@main

  call-reusable2:
    if: ${{ github.event.inputs.user_input == '2' }}
    uses: m9ksh1t/github-actions-demo/.github/workflows/reuse2.yml@main
