name: Reusable Workflow 1
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Echo greetings
        run: echo "AZURE DEPLOY"